---
# Python 3 with PostgreSQL
version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: nyu
    # ports:
    #   - 8000:8000
    volumes:
      - ..:/app
      - ~/.bluemix/:/home/devops/.bluemix/
    command: sleep infinity
    environment:
      FLASH_APP: service:app
      FLASK_ENV: development
      GUNICORN_BIND: "0.0.0.0:8000"
      DATABASE_URI: postgresql://postgres:postgres@postgres:5432/postgres
    networks:
      - dev
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres:

networks:
  dev: